import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '../components/header.js'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Bits & Bobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <div className={styles.box}>
          <img className={styles.logo} src="/Bits&Bobs Icon.png"/>
          <p className={styles.title}>bits & bobs</p>
        </div>

        <p className={styles.headline}>A simple but powerful app to keep track of your collections — a tracker for your personal items, experiences, and goals.</p>
        <p className={styles.desc}>We all have little things we want to keep track of. Maybe you’re looking to keep a record of your most prized possessions, a catalog of your vintage memorabilia, or your proudest collection of figurines. A top-10 list for your favorite movies you’ve watched or restaurants you’ve tried. Maybe a list of souvenirs from your favorite places you’ve visited, or even a checklist of all the places you want to visit in the future. Whatever you’re collecting, Bits & Bobs can help.</p>

        <a href="https://apps.apple.com/us/app/bits-and-bobs/id1554786457"><img src="download.svg" className={styles.download}/></a>

        <br/><br/><br/><br/><br/>
        
        
      </main>
    </>
  )
}
